version: '3'
services:
  redis:
    image: redis:4.0.8-alpine
    container_name: db-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./config:/docker/config
      - ./data:/data
    command: redis-server /docker/config/redis.conf