version: '3'

services:
  wc-api:
    build:
      context: .
    restart: always
    image: bigfei/wc-api
    container_name: wc-api
    environment:
      OKTA_OAUTH2_ISSUER: https://dev-wc-1.jp.auth0.com/
      OKTA_OAUTH2_CLIENT_ID: 7GH8oauy7bbsR6Dcd6zhHTbDNN9oqoqp
      OKTA_OAUTH2_CLIENT_SECRET: GZY__6pxqrK_TBpXOhFvHhJCABWIsof60MZWEGopbH3rYkbBzCOZTKP_ONztTsWO
    ports:
      - 8080:8080

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - configdb:/data/configdb
      - ./src/test/resources/mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoAdmin
      MONGO_INITDB_DATABASE: appdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoAdmin
    depends_on:
      - mongo

volumes:
  mongo:
  configdb: