### GET request with a header
GET http://localhost:8080/user/get/U001
Accept: application/json
token: 'sample token'


### GET request with a header
GET http://localhost:8080/user/getFriends/U001
Accept: application/json
token: 'sample token'
