spring:
  application:
    name: solutionapp
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: test
      password: test
  redis:
    database: 0
    host: localhost
    port: 6379
