#spring:
#  profiles:
#    active: dev
base-dbAddress: ${db.address:127.0.0.1}
base-dbPort: ${db.port:3306}
base-dbName: ${db.name:backend_test}
base-dbUserName: ${db.username:root}
base-dbPassword: ${db.password:1q2w3e4r}
base-dbUrl: jdbc:mysql://${base-dbAddress}:${base-dbPort}/${base-dbName}?characterEncoding=utf-8&serverTimezone=GMT%2B8
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: ${base-dbUrl}
    username: ${base-dbUserName}
    password: ${base-dbPassword}
  lifecycle:
    # 配置优雅关闭宽限时间
    timeout-per-shutdown-phase: 30s
  flyway:
    baseline-on-migrate: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  # 开启优雅关闭，默认：IMMEDIATE，立即关闭
  shutdown: graceful
  port: 8080
