spring:
  application:
    name: solutionapp
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root123456
  redis:
    database: 0
    host: localhost
    port: 6379