spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
  jackson:
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: user-service
# mybatis-plus:
#   type-handlers-package: com.craig.user.handler