spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/wiredcraft?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  redis:
    host: 127.0.0.1
    port: 6379
    password: H3yuncom

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.baomidou.mybatisplus.samples: debug
    tech.shoubi.aft: debug