server:
  port: 9001

spring:
  profiles:
    active: dev
  main:
    banner-mode: off

springfox:
  documentation:
    swagger-ui:
      enabled: true

mybatis-plus:
  global-config:
    banner: false
file:
  upload:
    path: C:/