version: '3.9'

services:
  db:
    image: mysql:8.0.29
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - ./redis/data:/demo/redis/data
      - ./redis/redis.conf:/demo/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server /demo/redis/redis.conf
