version: '3.1'

services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: ruczhang
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql