spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/wrdapp
    password: rootuser
  jpa:
    show:
      sql: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to Spring boot
server:
  port: '8082'
