name: CI

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Save Jar file
        uses: actions/upload-artifact@v3
        with:
          name: wc-api-jar
          path: target/*.jar
          retention-days: 14
