name: run-tests-on-push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JAVA 18
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          node-version: '18'
      - name: Test with maven
        run: mvn test --file pom.xml